name: EndRelay
version: '1.1'
main: ep1n.endRelay.EndRelay
api-version: '1.21'
authors: [ Ep1n ]
description: adds a better way to get around the end dimension
commands:
  relayrecipe:
    description: gives the recipe for an end relay