name: EndRelay
version: '1.0'
main: ep1n.endRelay.EndRelay
api-version: '1.21'
authors: [ Ep1n ]
description: adds a better way to get around the end dimension
commands:
  giveme:
    description: gives an end relay for the purposes of testing